name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@ba4004841e2a28c407fbf4b0633d2df8dc3ad7c4
    with:
      module: lsp
      verification-ref: ba4004841e2a28c407fbf4b0633d2df8dc3ad7c4
